language: python

sudo: false

python:
    - '3.4'

install:
    - pip install --upgrade pip
    - pip install pep8 nose coverage

script:
    - pep8 pyardrone
    - nosetests --with-coverage --cover-package pyardrone
